<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;

class AuthUsersTableSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {

        $users = array(
            array(
                'salutation' => 1,
                'first_name' => 'John',
                'middle_name' => 'James',
                'last_name' => 'McDonnell',
                'birthdate' => null,
                'mobile_telephone' => 8102242133,
                'home_telephone' => null,
                'work_telephone' => 8447363377,
                'address_one' => '207 Marion Street',
                'address_two' => null,
                'city' => 'Pinckney',
                'state' => 23,
                'zip' => 13338,
                'country' => 231,
                'fips' => null,
                'gender' => 1,
                'religion' => 20,
                'ethnicity' => null,
                'relationship_status' => null,
                'employer' => 'Renderlogic, Inc.',
                'military_rank' => 23,
                'veteran_status' => null,
                'student_status' => null,
                'email' => 'john@opticalvoltage.com',
                'username' => 'opticalvoltage',
                'password' => Hash::make("test"),
                'created_at_domain' => null,
                'role' => 0,
                'avatar_url' => null,
                'website' => 'https://www.renderlogic.com',
                'twitter_url' => 'https://twitter.com/renderlogic',
                'instagram_url' => 'https://www.instagram.com/renderlogic/',
                'facebook_url' => 'https://www.facebook.com/renderlogicinc',
                'confirmed' => true,
                'prospectified' => true,
                'email_verified_at' => null,
                'telephone_verified_at' => null,
                'user_banned' => false,
                'user_active' => true,
                'user_deliquent' => false,
                'first_login' => null,
                'last_login' => null,
                'created_visitor_ip' => null,
                'created_device_mac' => null,
                'last_visitor_ip' => null,
                'last_device_mac' => null,
                'remember_token' => null,
                'deleted_at' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => null
            ),
            array(
                'salutation' => 2,
                'first_name' => 'Jane',
                'middle_name' => 'Avery',
                'last_name' => 'Doe',
                'birthdate' => null,
                'mobile_telephone' => 5551211212,
                'home_telephone' => 1234561111,
                'work_telephone' => 8008001234,
                'address_one' => '13255 Random Street',
                'address_two' => 'Apartment 709',
                'city' => 'Dallas',
                'state' => 44,
                'zip' => 75201,
                'country' => 231,
                'fips' => null,
                'gender' => 2,
                'religion' => 5,
                'ethnicity' => null,
                'relationship_status' => null,
                'employer' => 'Acme, Inc.',
                'military_rank' => null,
                'veteran_status' => null,
                'student_status' => null,
                'email' => 'jane@renderlogic.com',
                'username' => 'jane',
                'password' => Hash::make("test"),
                'created_at_domain' => null,
                'role' => 3,
                'avatar_url' => null,
                'website' => 'https://www.renderlogic.com',
                'twitter_url' => 'https://twitter.com/renderlogic',
                'instagram_url' => 'https://www.instagram.com/renderlogic/',
                'facebook_url' => 'https://www.facebook.com/renderlogicinc',
                'confirmed' => true,
                'prospectified' => true,
                'email_verified_at' => null,
                'telephone_verified_at' => null,
                'user_banned' => false,
                'user_active' => true,
                'user_deliquent' => false,
                'first_login' => null,
                'last_login' => null,
                'created_visitor_ip' => null,
                'created_device_mac' => null,
                'last_visitor_ip' => null,
                'last_device_mac' => null,
                'remember_token' => null,
                'deleted_at' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => null
            ),
            array(
                'salutation' => 2,
                'first_name' => 'Valerie',
                'middle_name' => 'Ann',
                'last_name' => 'McDonnell',
                'birthdate' => null,
                'mobile_telephone' => 8107729461,
                'home_telephone' => null,
                'work_telephone' => 8008001234,
                'address_one' => '555 Random Street',
                'address_two' => null,
                'city' => 'Nashville',
                'state' => 44,
                'zip' => 75201,
                'country' => 231,
                'fips' => null,
                'gender' => 2,
                'religion' => 5,
                'ethnicity' => null,
                'relationship_status' => null,
                'employer' => 'Audatek, Inc.',
                'military_rank' => null,
                'veteran_status' => null,
                'student_status' => null,
                'email' => 'valerie@renderlogic.com',
                'username' => 'valerie',
                'password' => Hash::make("test"),
                'created_at_domain' => null,
                'role' => 2,
                'avatar_url' => null,
                'website' => null,
                'twitter_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'confirmed' => true,
                'prospectified' => true,
                'email_verified_at' => null,
                'telephone_verified_at' => null,
                'user_banned' => false,
                'user_active' => true,
                'user_deliquent' => false,
                'first_login' => null,
                'last_login' => null,
                'created_visitor_ip' => null,
                'created_device_mac' => null,
                'last_visitor_ip' => null,
                'last_device_mac' => null,
                'remember_token' => null,
                'deleted_at' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => null
            ),
            array(
                'salutation' => 1,
                'first_name' => 'John',
                'middle_name' => 'B.',
                'last_name' => 'Doe',
                'birthdate' => null,
                'mobile_telephone' => 8102630681,
                'home_telephone' => null,
                'work_telephone' => null,
                'address_one' => '6250 Random Street',
                'address_two' => null,
                'city' => 'Detroit',
                'state' => 23,
                'zip' => 75201,
                'country' => 231,
                'fips' => null,
                'gender' => 1,
                'religion' => 6,
                'ethnicity' => null,
                'relationship_status' => null,
                'employer' => 'Optical Voltage, Inc.',
                'military_rank' => null,
                'veteran_status' => null,
                'student_status' => null,
                'email' => 'employee@renderlogic.com',
                'username' => 'employee_account',
                'password' => Hash::make("test"),
                'created_at_domain' => null,
                'role' => 1,
                'avatar_url' => null,
                'website' => 'https://www.opticalvoltage.com',
                'twitter_url' => null,
                'instagram_url' => null,
                'facebook_url' => null,
                'confirmed' => true,
                'prospectified' => true,
                'email_verified_at' => null,
                'telephone_verified_at' => null,
                'user_banned' => false,
                'user_active' => true,
                'user_deliquent' => false,
                'first_login' => null,
                'last_login' => null,
                'created_visitor_ip' => null,
                'created_device_mac' => null,
                'last_visitor_ip' => null,
                'last_device_mac' => null,
                'remember_token' => null,
                'deleted_at' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => null
            )
        );
        for ($i = 0; $i < count($users); $i++) {
            \DB::table('auth_users')->insert([
                'salutation' => $users[$i]['salutation'],
                'first_name' => $users[$i]['first_name'],
                'middle_name' => $users[$i]['middle_name'],
                'last_name' => $users[$i]['last_name'],
                'birthdate' => $users[$i]['birthdate'],
                'mobile_telephone' => $users[$i]['mobile_telephone'],
                'home_telephone' => $users[$i]['home_telephone'],
                'work_telephone' => $users[$i]['work_telephone'],
                'address_one' => $users[$i]['address_one'],
                'address_two' => $users[$i]['address_two'],
                'city' => $users[$i]['city'],
                'state' => $users[$i]['state'],
                'zip' => $users[$i]['zip'],
                'country' => $users[$i]['country'],
                'fips' => $users[$i]['fips'],
                'gender' => $users[$i]['gender'],
                'religion' => $users[$i]['religion'],
                'ethnicity' => $users[$i]['ethnicity'],
                'relationship_status' => $users[$i]['relationship_status'],
                'employer' => $users[$i]['employer'],
                'military_rank' => $users[$i]['military_rank'],
                'veteran_status' => $users[$i]['veteran_status'],
                'student_status' => $users[$i]['student_status'],
                'email' => $users[$i]['email'],
                'username' => $users[$i]['username'],
                'password' => $users[$i]['password'],
                'created_at_domain' => $users[$i]['created_at_domain'],
                'role' => $users[$i]['role'],
                'avatar_url' => $users[$i]['avatar_url'],
                'website' => $users[$i]['website'],
                'twitter_url' => $users[$i]['twitter_url'],
                'instagram_url' => $users[$i]['instagram_url'],
                'facebook_url' => $users[$i]['facebook_url'],
                'confirmed' => $users[$i]['confirmed'],
                'prospectified' => $users[$i]['prospectified'],
                'email_verified_at' => $users[$i]['email_verified_at'],
                'telephone_verified_at' => $users[$i]['telephone_verified_at'],
                'user_banned' => $users[$i]['user_banned'],
                'user_active' => $users[$i]['user_active'],
                'user_deliquent' => $users[$i]['user_deliquent'],
                'first_login' => $users[$i]['first_login'],
                'last_login' => $users[$i]['last_login'],
                'created_visitor_ip' => $users[$i]['created_visitor_ip'],
                'created_device_mac' => $users[$i]['created_device_mac'],
                'last_visitor_ip' => $users[$i]['last_visitor_ip'],
                'last_device_mac' => $users[$i]['last_device_mac'],
                'remember_token' => $users[$i]['remember_token'],
                'deleted_at' => $users[$i]['deleted_at'],
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => $users[$i]['updated_at']
            ]);
        }
    }

}
